mgit/mgit/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls'))
]

mgit/website/urls.py
from django.urls import path
from website import views

app_name = 'website'

urlpatterns = [

        path('',views.home,name='home1'),
        path('Home',views.Home,name='home'),
        path('spotlight',views.spotlight,name='spotlight'),
        path('dop',views.photo,name='dop'),
        path('literary',views.literary,name='literary'),
        path('login/',views.userlogin,name='login'),
        # path('user/<int:pk>/',views.userinfo,name='user'),
        path('user/',views.userinfo1,name='userinfo'),
        path('logout/',views.userlogout,name='logout'),
        path('registraion/',views.registration,name='signup'),
        path('literary/newpost/',views.newposter,name='newpost'),
        path('literary/newpost/comment/<int:pk>/',views.comments,name='comments'),
        path('literary/publish/<int:pk>/',views.publish,name='publish'),
        path('music/',views.comming,name='comming'),
        path('dance/',views.comming,name='comming1'),




]

mgit/website/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class BlogContent(models.Model):
#         user = models.OneToOneField(User,on_delete=models.CASCADE)
#         Title = models.CharField(max_length = 20)
#         content = models.CharField(max_length=5000)
#         def __str__():
#             return self.user.username
#

class Mgituser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    Roll_number = models.CharField(max_length = 10)

    def __str__(self):
        return self.Roll_number

class BlogContent11(models.Model):


    user  = models.ForeignKey(User,related_name='stories',on_delete=models.CASCADE)
    title = models.CharField(max_length = 50)
    story = models.CharField(max_length=5000)
    publish = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username


class PublishUser(models.Model):
    title = models.CharField(max_length = 50)
    story = models.CharField(max_length=5000)
    author = models.CharField(max_length=100)
    def __str__(self):
        return self.title


class CommentUser(models.Model):
    post = models.ForeignKey(PublishUser,on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    def __str__(self):
        return self.post.title

mgit/website/forms.py
from django import forms
from django.forms import ModelForm
from website.models import *
from django.contrib.auth.models import User

# class BlogForm(forms.ModelForm):
#     class Meta():
#         model = 'BlogContent'
#         fields = ('Title','content')


class authenticateform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields =('username','email','password')

class BlogContent1Form(forms.ModelForm):
    class Meta():
        model = BlogContent11
        fields = ('title','story')


class CommentForms(forms.ModelForm):
    class Meta():
        model = CommentUser
        fields = ('comment',)


class MgitForms(forms.ModelForm):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    class Meta():
        model = Mgituser
        fields = ('Roll_number',)

mgit/website/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from website.models import *
from website.forms import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
import json
import requests

# Create your views here.
def Home(request):
    return render(request,'website/home.html')


def home(request):
    return render(request,'website/home1.html')


def spotlight(request):
    return render(request,'website/spotlight.html')


def photo(request):
    return render(request,'website/dop.html')

def literary(request):
    objects =PublishUser.objects.order_by('-id')
    context = {'lists':objects}
    return render(request,'website/literary.html',context)

def comming(request):
    return render(request,'website/cmg.html')






def userlogin(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('website:home',))
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('pass')
            user = authenticate(username= username,password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('website:home'))
                else:
                    return HttpResponse("Account not active")
            else:
                print("someone tried to login and failed ")
                print(f"Username :{username} and password :{password}")
                return HttpResponse("Invalid login credentials")

        else:
            return render(request,'website/login.html',context={})


# @login_required
# def userinfo(request,pk):
#      model = User.objects.get(id=pk)
#      model1 = model.stories.order_by('-id')
#      print(model)
#      context = {'objects':model1}
#      return render(request,'website/user.html',context)
#


@login_required
def userinfo1(request):
     pk = request.user.id
     model = User.objects.get(id=pk)
     model1 = model.stories.order_by('-id')
     print(model)
     context = {'objects':model1}
     return render(request,'website/user.html',context)


@login_required
def userlogout(request):
        logout(request)
        return HttpResponseRedirect(reverse('website:home'))






def registration(request):
    registered = False
    if request.method == "POST":


        user_form = authenticateform(request.POST)
        mgit_form = MgitForms(request.POST)
        clientkey = request.POST['g-recaptcha-response']
        secretkey = "6LdW1awZAAAAAAywOAedFlMEXxgwhWACCfPaOHDv"
        sdata = {
                'secret':secretkey,
                'response': clientkey
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify',data=sdata)
        response = json.loads(r.text)
        verify = response['success']
        print(verify)
        if verify:

            if user_form.is_valid() and  mgit_form.is_valid():
                username = user_form.cleaned_data.get('username')
                password = user_form.cleaned_data.get('password')
                email = user_form.cleaned_data.get('email')
                roll = mgit_form.cleaned_data.get('Roll_number')

                print(username,password)
                user_obj = User(username=username,password= password,email=email)
                mgit_obj = Mgituser(Roll_number=roll)
                mgit_obj.user = user_obj

                user_obj.set_password(user_obj.password)


                user_obj.save()

                mgit_obj.save()


                registered = True

                context={"registered":registered}

                return render(request,'website/signup.html',context)
            else:
                HttpResponse(user_form.errors)
                HttpResponse(mgit_form.errors)

        else:
            HttpResponse('<script> alert("Are you a robot"); </script>')
    else:

        context={"registered":registered}
        return render(request,'website/signup.html',context)



@login_required
def newposter(request):
    if request.method == "POST":
        clientkey = request.POST['g-recaptcha-response']
        secretkey = "6LdW1awZAAAAAAywOAedFlMEXxgwhWACCfPaOHDv"
        sdata = {
                'secret':secretkey,
                'response': clientkey
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify',data=sdata)
        response = json.loads(r.text)
        verify = response['success']
        print(verify)
        if verify:
            form = BlogContent1Form(request.POST)
            print('hello1')
            if form.is_valid():
                print('hello2')

                # form.user=user
                # form.save()
                user1= request.user

                user = User.objects.get(id=user1.id)
                # user = request.user.userna
                title = form.cleaned_data['title']
                story = form.cleaned_data['story']


                print('hello3')

                form11 = BlogContent11(user=user,title=title,story=story)

                print('hello4')
                form11.save()
                print('hello5s')
                return HttpResponseRedirect(reverse('website:userinfo'))
            else:
                print(form.errors)
        else:
            HttpResponse('<script> alert("Are you a robot"); </script>')

    else:
        return render(request,'website/newpost.html')






def publish(request,pk):
    content = BlogContent11.objects.get(id=pk)

    print('hello')
    if request.method == "POST":
        print('hello')
        author = request.POST['user']
        title = request.POST['title']
        story = request.POST['story']
        model = PublishUser(author=author,title=title,story=story)
        model.save()
        content = BlogContent11.objects.get(id=pk)
        content.publish = True
        content.save()


        return HttpResponseRedirect(reverse('website:literary'))


def comments(request,pk):
    if request.method == 'POST':
        form = CommentForms( request.POST)
        if form.is_valid():

            content = form.cleaned_data['comment']

            user = PublishUser.objects.get(id=pk)

            model = CommentUser(post=user,comment=content)
            model.save()

            return HttpResponseRedirect(reverse('website:literary'))
        else:
            print(form.errors)
            return HttpResponse("Comment Failed1")

    else:
        return HttpResponse("Comment Failed")

mgit/website/templates/website/cmg.html
{% extends 'website/index.html' %}
{% block content %}
<div class="container" id='luhar' style="margin-top:7%; ">
  <div class="jumbotron"style=" text-align:center;" >
      <h1 >COMING </h1>
      <h1>SOON</h1>
  </div>

</div>
{% endblock %}

mgit/website/templates/website/dop.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Mgit Clubs</title>
    <!-- CSS only -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
          <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <link rel="stylesheet" href="{% static 'css/dop.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id='navbar'>
                <a class="navbar-brand" href="#">
          <img src="{% static 'img/mgit2.png' %}" width="75px" height="auto" class="d-inline-block align-top" alt="" loading="lazy">
          </a>
          <a href="{% url 'website:home' %}" class='navbar-brand' id ='brand'>Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <!-- <li class="nav-item active">
                <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:spotlight' %}">Spotlight</a>
              </li>
              <li class="nav-item">
                <a class="nav-link "href="{% url 'website:dop' %}"  >Dop</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'website:literary' %}"  >LiteraryClub</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'website:comming' %}"  >MusicClub </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'website:comming1' %}"  >DanceClub</a>
              </li>
            </ul>


            {% if user.is_authenticated %}
              <a href="{% url 'website:userinfo' %}"><button class="btn btn-outline-success my-2 my-sm-4 " type="submit">{{user.username}}</button></a>
            {% else %}
                <a href="{% url 'website:login' %}"><button class="btn btn-outline-success my-2 my-sm-4 " type="submit">login</button></a>
                {% endif %}



          </div>
        </nav>
            <div class="dp-cam5">
              <div class="dp-lig">
                <h2>LIGHTS</h2>
                <h2>CAMERA</h2>
                <h2>CAPTURE</h2>

              </div>

                <img src="{%static 'img/cam5.jpg' %}" class='dp-cam'>
              </div>


              <div class="container-fluid" id ="dp-img3">
                <div class="container">
                  <div class="jumbotron">
                    <h2 style='text-align:center;' > Some Moments captured by our Team</h2>

                  </div>

                </div>

                 <div class="rowa" id='row'>
                  <div class=" " ><img class="img-thumbnail img-fluid" src="{% static 'img/dop/1.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/2.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/3.png' %}" alt=""></div>
                  <div class="  "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/4.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/5.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/6.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/7.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/8.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/9.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/10.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/11.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/12.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/13.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/14.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/15.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/16.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/17.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/18.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/19.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/20.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/21.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/22.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/23.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/24.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/25.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/26.png' %}" alt=""></div>
                  <div class=" "><img class="img-thumbnail img-fluid" src="{% static 'img/dop/27.png' %}" alt=""></div>



                </div>
              </div><!-- /.container -->










         <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>




  </body>
   </html>

mgit/website/templates/website/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Mgit Clubs</title>
    <!-- CSS only -->

      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=EB+Garamond&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@300&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Holtwood+One+SC&family=Piedra&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Stylish&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&family=Special+Elite&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Shadows+Into+Light&family=Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Holtwood+One+SC&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id='navbar'>
                <a class="navbar-brand" href="#">
          <img src="{% static 'img/mgit2.png' %}" width="75px" height="auto" class="d-inline-block align-top" alt="" loading="lazy">
          </a>
          <a href="{% url 'website:home' %}" class='navbar-brand' id ='brand'>Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <!-- <li class="nav-item active">
                <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:spotlight' %}">Spotlight</a>
              </li>
              <li class="nav-item">
                <a class="nav-link "href="{% url 'website:dop' %}"  >Dop</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'website:literary' %}"  >LiteraryClub</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'website:comming' %}"  >MusicClub </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'website:comming1' %}"  >DanceClub</a>
              </li>
            </ul>


            {% if user.is_authenticated %}
            <a href="{% url 'website:userinfo' %}"><button class="btn btn-outline-success nav-link  " type="submit">{{user.username}}</button></a>
            {% else %}
                <a href="{% url 'website:login' %}"><button class="btn btn-outline-success nav-link " type="submit">login</button></a>
                {% endif %}



          </div>
        </nav>


        {% block content %}


        {% endblock %}





<!--
       -->



       <script src="https://www.google.com/recaptcha/api.js" async defer></script>

       <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
       <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
       <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>




  </body>
</html>

mgit/website/templates/website/literary.html
{% extends 'website/index.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
  <div class="jumbotron" id='after' style='margin-top:7%;'>
    <h1 >Hi</h1>

    <h3>In this people can write their own stories</h3>
    <h3>We hope you to write some weird stories</h3>

  </div>

</div>
<div class="container " id='rahul' class='lit-rahul' style='margin-top:7%;' >
  <form  method="post">
    {% csrf_token %}

    <a href="{% url 'website:newpost' %}"><button type="button" class='btn btn-primary' style="float:right;" name="button">NEW POST</button></a>
  </form>
  <h1>Posts:</h1>
</div>

{% for item in lists %}
<div class="container" id='lit-post-ct'>
  <div class="jumbotron" id="what1">
    <h1 class='hello' id='luhar' >{{item.title}}</h1>
    <textarea name="name" readonly rows="8" cols="80" class='form-control ' id='story'>

      {{item.story}}

    </textarea>
    <div class="storyby">
        <small >Story by:<p>{{item.author}}</p></small>
    </div>
    <div class="container">
        <p>
            <a  data-toggle="collapse" href="#hellooooo{{item.id}}" role="button" aria-expanded="false" aria-controls="hellooooo{{item.id}}">
              Comments
            </a>
            </p>
            <div class="collapse" id="hellooooo{{item.id}}">
            <div class="card card-body">

              <form  action="{% url 'website:comments' pk=item.id %}" method="post">
                  {% csrf_token  %}
                  <p>
                    <label for="">Comment:</label>
                    <input class="form-control" type="text" name="comment" value="">
                    </p>
                    <input  class='btn btn-primary' id='wow' type="Submit" name="" value="Submit">
              </form>
              <hr>
              <h4>All Comments:</h4>
              {% for stud in item.comments.all %}
              <ul class="list-group list-group-flush">
                <li class="list-group-item ">{{stud.comment}}</li>

              </ul>
              {% endfor %}


            </div>
            </div>


      </div>


  </div>

</div>
{% endfor %}
{% else %}
<div class="container">
  <div class="jumbotron" id='luhar' style='margin-top:7%;'>
    <h1>You need to Login to See this Page</h1>

  </div>

</div>
{% endif %}
{% endblock %}

mgit/website/templates/website/login.html
{% extends "website/index.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron" id='login'>

    <h1>Please Login:</h1>
    <!-- <small>Must be a superuser </small> -->
    <hr>
        <form method='post'>
          {% csrf_token %}
      <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
          <input type="text"  class="form-control"  name="username"  placeholder="Username">
        </div>
      </div>
      <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="pass">
        </div>
      </div>
      <div class="form-group row" id='button'>
      <p align='right'><input type="submit" class= 'btn btn-primary '  name="" value="Login"></p>

    </div>

    </form>
    <p></p>
    <small>Don't have an account??  <a href="{% url 'website:signup' %}"> signup</a></small>


  </div>
</div>

{% endblock %}

mgit/website/templates/website/user.html
{% extends "website/index.html" %}
{% block content %}

<div class="container"  id='user-mgit' >
  <div class="jumbotron" style='margin-top:7%; background-color:white' >
    <form method='get'>


  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
    <div class="col-sm-10">
      <input type="text"  class="form-control" disabled  value='{{user.username}}' name="username"  >
    </div>
  </div>
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Roll Number</label>
    <div class="col-sm-10">
      <input type="text"  class="form-control" disabled  value='{{user.mgituser.Roll_number}}' name="username" >
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputPassword" disabled value='{{user.email}}' name="pass">

    </div>
  </div>
</form>

<a href="{% url 'website:logout' %}"><button class="btn btn-outline-success my-2 my-sm-4 " type="submit">logout</button></a>
<br>
<small>Your Published Stories can be viewed in Literary Club</small>

  </div>

</div>
<div class="container" id='user-posts'>
  <div class="jumbotron" id='posts'>
      <ol>
    {% for stud in objects %}



        <li>
          <form method="post" action="{% url 'website:publish' pk=stud.id %}">
                    {% csrf_token %}
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Author</label>
            <div class="col-sm-10">
              <input type="text" name = "user" readonly class="form-control" id="staticEmail" value={{user.username}} >
            </div>
          </div>
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input type="text"  readonly class="form-control" id="staticEmail" name='title' value={{stud.title}}>
            </div>
          </div>
          <div class="form-group row">
                <label for="inputPassword" class="col-sm-2 col-form-label">Text</label>
              <div class="col-sm-10">
              <textarea name="story" readonly rows="8" cols="80" class='form-control' id='story' >{{stud.story}}</textarea>
              </div>
          </div>
          <div class="form-group row">
            {% if stud.publish  %}
            <div class="col-lg-4">
              <input type="submit" name=""  disabled class='btn btn-dark' value="Published">
            </div>
            {% else %}
              <div class="col-lg-4">
                <input type="submit" name="" class='btn btn-primary'value="Publish">
              </div>
              {% endif %}
          </div>
        </form>
      </li>

    <hr>
      {% endfor %}
    </ol>


    </div>

  </div>

{% endblock %}